#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys

from urllib2 import urlopen, Request
import re
import hashlib
from os.path import join

CATEGORY = 'stegano'
SCORE = 500
NAME = "Echo"

SHOUTCAST_SERVER = 'http://172.16.16.1:8000/'
SONG_TITLE_REGEX = r'Current Song:</td>\n<td class="streamdata">(?:.+?) - (.+?)</td>'

TIMEOUT = 120

HTML_EN = ''' Don't expect anything original from <a href="http://echo.quals.ructf.org:8000/echo.ogg">an echo</a>. Формат флага — "RUCTF_.*"'''
HTML_RU = ''' Не ожидайте чего-то оригинального от <a href="http://echo.quals.ructf.org:8000/echo.ogg">эхо</a>. Flag format — "RUCTF_.*"'''

if len(sys.argv) < 2:
    sys.stderr.write("You need to provide at least one argument\n")
    exit(1)

action = sys.argv[1].lower()


def md5(mess):
    h = hashlib.md5()
    h.update(mess.encode())
    return h.hexdigest()


def check_task(answer):
    req = Request(SHOUTCAST_SERVER)
    req.add_header('User-Agent', 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.146 Safari/537.36')
    page = urlopen(req).read().decode('utf-8')
    m = re.search(SONG_TITLE_REGEX, page)
    if not m:
        sys.stderr.write('Failed to find pattern!')
        return False
    else:
        title = m.group(1)
        sys.stderr.write('Title: %s\n' % title)
        corrent_ans = 'RUCTF_' + md5(title)
        return corrent_ans.lower() == answer.lower()



if action == 'id':
    print("{}:{}".format(CATEGORY, SCORE))
elif action == 'series':
    print(CATEGORY)
elif action == 'name':
    print(NAME)
elif action == 'create':
    print("html[en]:{}".format(HTML_EN))
    print("html[ru]:{}".format(HTML_RU))
elif action == 'user':
    answer = sys.stdin.readline().strip()
    status = check_task(answer)
    stat = 0 if status else 1
    exit(stat)
else:
    sys.stderr.write("No such action: '{}' available actions are: id, series, name, create, user".format(action))
    exit(1)

exit(0)